name: flutter_with_lua
description: flutter use dart ffi api with lua .
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  dart_lua_ffi: ^0.0.1-dev.1
  flutter:
    sdk: flutter
  path_provider: ^2.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: top.autopc.flutter_with_lua
        pluginClass: FlutterWithLuaPluginy
